# Generated by Django 6.1 on 2026-09-13 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import user.module_encrypted_field


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Адрес электронной почты пользователя.",
                max_length=254,
                unique=True,
                verbose_name="e-mail",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Имя пользователя в системе, которое должно соответствовать регулярному выражению.",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="«Нельзя использовать пробел и символы, кроме . @ + - _».",
                        regex="^[\\w.@+-]+$",
                    )
                ],
                verbose_name="имя пользователя в системе",
            ),
        ),
        migrations.CreateModel(
            name="TInvestAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=50, unique=True)),
                (
                    "access_token",
                    user.module_encrypted_field.CustomEncryptedCharField(
                        help_text="api key токен с доступом к конкретному счету T инвестиции",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Краткое описание...", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="real_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
