# Generated by Django 6.1 on 2026-09-13 16:04

from django.db import migrations

import user.module_encrypted_field


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_email_alter_user_username_tinvestaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tinvestaccount",
            name="access_token",
            field=user.module_encrypted_field.CustomEncryptedCharField(
                help_text="api key токен с доступом к конкретному счету T инвестиции",
                max_length=512,
            ),
        ),
    ]
